apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-config
  namespace: workflow-system
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  MYSQL_HOST: "mysql.workflow-system.svc.cluster.local"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  SERVER_PORT: "8080"