apiVersion: v1
kind: Service
metadata:
  name: workflow-service
  namespace: workflow-system
spec:
  selector:
    app: workflow-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP